Fine Tuned Bayesian Ridge. Didn't Drop 'Time_of_service' column.

In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv("Train.csv")
test_data = pd.read_csv("Test.csv")
trndata = train_data
tstdata = test_data

In [3]:
train_data.head(2)

Employee_ID Gender   Age  Education_Level  ... VAR5 VAR6 VAR7 Attrition_rate
0   EID_23371      F  42.0                4  ...    4    5    3         0.1841
1   EID_18000      M  24.0                3  ...    3    5    3         0.0670

[2 rows x 24 columns]

In [ ]:
train_data.isnull().sum()

Employee_ID                    0
Gender                         0
Age                          412
Education_Level                0
Relationship_Status            0
Hometown                       0
Unit                           0
Decision_skill_possess         0
Time_of_service              144
Time_since_promotion           0
growth_rate                    0
Travel_Rate                    0
Post_Level                     0
Pay_Scale                      9
Compensation_and_Benefits      0
Work_Life_balance             11
VAR1                           0
VAR2                         577
VAR3                           0
VAR4                         656
VAR5                           0
VAR6                           0
VAR7                           0
Attrition_rate                 0
dtype: int64

In [ ]:
# train_data = train_data.drop('Time_of_service',1)
# test_data = test_data.drop('Time_of_service',1)

In [4]:
train_data.head(10)

Employee_ID Gender   Age  Education_Level  ... VAR5 VAR6 VAR7 Attrition_rate
0   EID_23371      F  42.0                4  ...    4    5    3         0.1841
1   EID_18000      M  24.0                3  ...    3    5    3         0.0670
2    EID_3891      F  58.0                3  ...    3    8    3         0.0851
3   EID_17492      F  26.0                3  ...    3    7    3         0.0668
4   EID_22534      F  31.0                1  ...    2    8    2         0.1827
5    EID_2278      M  54.0                3  ...    2    8    3         0.7613
6   EID_18588      F  21.0                4  ...    3    7    3         0.2819
7    EID_1235      F   NaN                3  ...    3    9    3         0.1169
8   EID_10197      M  40.0                4  ...    5    6    3         0.1968
9   EID_21262      M  45.0                3  ...    4    8    3         0.2870

[10 rows x 24 columns]

In [5]:
train_data['Age'].fillna((train_data['Age'].mean()), inplace=True)
train_data['VAR2'].fillna((train_data['VAR2'].mean()), inplace=True)
train_data['Pay_Scale'].fillna((train_data['Pay_Scale'].mean()), inplace=True)
train_data['Work_Life_balance'].fillna((train_data['Work_Life_balance'].mean()), inplace=True)
train_data['VAR4'].fillna((train_data['VAR4'].mean()), inplace=True)
train_data['Time_of_service'].fillna((train_data['Time_of_service'].mean()), inplace=True)

In [6]:
test_data['Age'].fillna((test_data['Age'].mean()), inplace=True)
test_data['VAR2'].fillna((test_data['VAR2'].mean()), inplace=True)
test_data['Pay_Scale'].fillna((test_data['Pay_Scale'].mean()), inplace=True)
test_data['Work_Life_balance'].fillna((test_data['Work_Life_balance'].mean()), inplace=True)
test_data['VAR4'].fillna((test_data['VAR4'].mean()), inplace=True)
test_data['Time_of_service'].fillna((test_data['Time_of_service'].mean()), inplace=True)

In [7]:
train_data = train_data.drop('Employee_ID', 1)
test_data = test_data.drop('Employee_ID', 1)
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.columns

Index(['Age', 'Education_Level', 'Time_of_service', 'Time_since_promotion',
       'growth_rate', 'Travel_Rate', 'Post_Level', 'Pay_Scale',
       'Work_Life_balance', 'VAR1', 'VAR2', 'VAR3', 'VAR4', 'VAR5', 'VAR6',
       'VAR7', 'Attrition_rate', 'Gender_F', 'Gender_M',
       'Relationship_Status_Married', 'Relationship_Status_Single',
       'Hometown_Clinton', 'Hometown_Franklin', 'Hometown_Lebanon',
       'Hometown_Springfield', 'Hometown_Washington',
       'Unit_Accounting and Finance', 'Unit_Human Resource Management',
       'Unit_IT', 'Unit_Logistics', 'Unit_Marketing', 'Unit_Operarions',
       'Unit_Production', 'Unit_Purchasing', 'Unit_Quality', 'Unit_R&D',
       'Unit_Sales', 'Unit_Security', 'Decision_skill_possess_Analytical',
       'Decision_skill_possess_Behavioral',
       'Decision_skill_possess_Conceptual', 'Decision_skill_possess_Directive',
       'Compensation_and_Benefits_type0', 'Compensation_and_Benefits_type1',
       'Compensation_and_Benefits_type2', '

In [8]:
dummyvarlist = ['Gender_F', 'Relationship_Status_Married', 'Hometown_Clinton', 'Unit_IT',
                'Decision_skill_possess_Analytical', 'Compensation_and_Benefits_type0']
for i in dummyvarlist:
  train_data = train_data.drop(str(i), 1)
  test_data = test_data.drop(str(i), 1)

In [9]:
train_data.shape

(7000, 41)

In [10]:
train_data.head(1)

Age  ...  Compensation_and_Benefits_type4
0  42.0  ...                                0

[1 rows x 41 columns]

In [42]:
X = train_data.drop('Attrition_rate', 1).values
X_test = test_data.iloc[:, :].values
y = train_data.iloc[:, 16].values

In [43]:
X[1]

array([24.    ,  3.    ,  5.    ,  4.    , 36.    ,  0.    ,  3.    ,
        6.    ,  4.    ,  3.    , -0.9612, -0.4537,  2.    ,  3.    ,
        5.    ,  3.    ,  1.    ,  1.    ,  0.    ,  0.    ,  1.    ,
        0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
        0.    ,  0.    ,  1.    ,  0.    ,  0.    ])

In [ ]:
# from sklearn.preprocessing import OneHotEncoder 
# from sklearn.compose import ColumnTransformer 

# # creating one hot encoder object with categorical feature 0 
# # indicating the first column 
# columnTransformer = ColumnTransformer([('encoder', 
# 										OneHotEncoder(), 
# 										[0, 3, 4, 5, 6, 13])], 
# 									remainder='passthrough') 

# X = np.array(columnTransformer.fit_transform(X), dtype = np.str) 
# X_test = np.array(columnTransformer.fit_transform(X_test), dtype = np.str) 

In [44]:
X[1].reshape(1, -1)

array([[24.    ,  3.    ,  5.    ,  4.    , 36.    ,  0.    ,  3.    ,
         6.    ,  4.    ,  3.    , -0.9612, -0.4537,  2.    ,  3.    ,
         5.    ,  3.    ,  1.    ,  1.    ,  0.    ,  0.    ,  1.    ,
         0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  1.    ,  0.    ,  0.    ]])

In [47]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')
nanlist = [1, 6, 7, 12, 14, 16, 18]
for i in nanlist:
  X[i] = (impute.fit_transform(X[i].reshape(1, -1)))
  X_test[i] = (impute.fit_transform(X_test[i].reshape(1, -1)))

In [48]:
X = X.astype('float64')
X_test = X_test.astype('float64')

In [50]:
 from sklearn.model_selection import GridSearchCV
 params = {
 'alpha_1' : [1, 0.1, 0.01, 0.001, 0.0001, 0],
 'alpha_2' : [1, 0.1, 0.01, 0.001, 0.0001, 0],
 'n_iter' : [5, 7, 10, 12, 15, 20, 25, 50, 100],
  'tol' : [1, 0.1, 0.001, 0.0001]
 }

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

In [53]:
from sklearn.linear_model import BayesianRidge, LinearRegression, Lasso, ElasticNet
model = BayesianRidge()
grid = GridSearchCV(estimator=model, param_grid = params)
grid.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=BayesianRidge(alpha_1=1e-06, alpha_2=1e-06,
                                     alpha_init=None, compute_score=False,
                                     copy_X=True, fit_intercept=True,
                                     lambda_1=1e-06, lambda_2=1e-06,
                                     lambda_init=None, n_iter=300,
                                     normalize=False, tol=0.001,
                                     verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha_1': [1, 0.1, 0.01, 0.001, 0.0001, 0],
                         'alpha_2': [1, 0.1, 0.01, 0.001, 0.0001, 0],
                         'n_iter': [5, 7, 10, 12, 15, 20, 25, 50, 100],
                         'tol': [1, 0.1, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [54]:
print(grid)
# summarize the results of the grid search
print(grid.best_score_)
print(grid.best_estimator_)

GridSearchCV(cv=None, error_score=nan,
             estimator=BayesianRidge(alpha_1=1e-06, alpha_2=1e-06,
                                     alpha_init=None, compute_score=False,
                                     copy_X=True, fit_intercept=True,
                                     lambda_1=1e-06, lambda_2=1e-06,
                                     lambda_init=None, n_iter=300,
                                     normalize=False, tol=0.001,
                                     verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha_1': [1, 0.1, 0.01, 0.001, 0.0001, 0],
                         'alpha_2': [1, 0.1, 0.01, 0.001, 0.0001, 0],
                         'n_iter': [5, 7, 10, 12, 15, 20, 25, 50, 100],
                         'tol': [1, 0.1, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)
-0.001354380404841038
BayesianRidge(alpha_1=0, alpha_2=1, alpha_ini

In [68]:
model = BayesianRidge(alpha_1 = 0, alpha_2 = 1, lambda_1 = 1, lambda_2 = 0,
                      n_iter = 6)

In [69]:
model.fit(X, y)

BayesianRidge(alpha_1=0, alpha_2=1, alpha_init=None, compute_score=False,
              copy_X=True, fit_intercept=True, lambda_1=1, lambda_2=0,
              lambda_init=None, n_iter=6, normalize=False, tol=0.001,
              verbose=False)

In [70]:
accuracy = model.score(x_test, y_test)
accuracy

0.00043386041442106116

In [71]:
preds = model.predict(X_test)
preds

array([0.19138179, 0.18898295, 0.18119961, ..., 0.18448223, 0.18104928,
       0.19273134])

In [72]:
rows = zip(tstdata['Employee_ID'], preds)
import csv
with open('bayesian_ridge_3.csv', "w") as f:
    writer = csv.writer(f)
    for row in rows:
        writer.writerow(row)

In [73]:
df = pd.read_csv('bayesian_ridge_3.csv', header=None)
df.rename(columns={0: 'Employee_ID', 1: 'Attrition_rate'}, inplace=True)
df.to_csv('bayesian_ridge_3.csv', index=False) # save to new csv file